#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# define variables
FILE_TO_TRANSFER='$1'
SERVER_IP='$2'
SERVER_USER='$3'
SSH_KEY='$4'

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
