#!/usr/bin/env bash
# install nginix in a sever

sudo apt-get update
sudo apt-get install -y nginx ufw
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
