#!/usr/bin/env bash
# install nginix in a sever

sudo apt-get update
sudo apt-get install -y nginx ufw
sudo ufw allow 'Nginx HTTP'

sudo su
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
