#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo pat-get -y install nginx

sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
