#!/usr/bin/env bash
#script that displays Best School 10 times for 9th iteration display hi.


for ((index = 1; index <= 10; index++))
do
	echo "Best School"
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
done
